name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Debug folder content
        run: ls -R public/

      - name: Upload files to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: public/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'frontend'
