name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Gunakan v4, bukan v3!
        with:
          name: pages-artifact
          path: public  # Pastikan folder ini berisi index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
